apiVersion: v1
kind: Service
metadata:
  labels:
    app: question-server
  name: question-server
spec:
  ports:
    - name: tls-common
      port: 443
      protocol: TCP
      targetPort: 9015
  selector:
    app: question-server
  type: ClusterIP