apiVersion: v1
kind: Service
metadata:
  labels:
    app: gondola-server
  name: gondola-server
spec:
  ports:
    - name: tls-common
      port: 443
      protocol: TCP
      targetPort: 9016
  selector:
    app: gondola-server
  type: ClusterIP