apiVersion: v1
kind: Service
metadata:
  labels:
    app: bazooka-server
  name: bazooka-server
spec:
  ports:
    - name: tls-common
      port: 443
      protocol: TCP
      targetPort: 9010
  selector:
    app: bazooka-server
  type: ClusterIP